<?php

namespace App\Filament\Resources;

use App\Filament\Resources\GameResource\Pages;
use App\Models\Category;
use App\Models\Game;
use Filament\Forms;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class GameResource extends Resource
{
    protected static ?string $model = Game::class;

    protected static ?string $navigationIcon = 'heroicon-o-puzzle-piece';

    protected static ?string $navigationLabel = 'Slotegrator Games';

    protected static ?string $modelLabel = 'Slotegrator Games';

    protected static ?string $navigationGroup = 'My Game';

    protected static ?string $slug = 'my-game';

    protected static ?string $recordTitleAttribute = 'name';

    protected static ?int $navigationSort = 1;

    /**
     * @return string|null
     */
    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string|array|null
     */
    public static function getNavigationBadgeColor(): string|array|null
    {
        return static::getModel()::count() > 5 ? 'success' : 'warning'; // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Games')
                    ->description(__('admin.Registering_game'))
                    ->schema([
                        Forms\Components\Select::make('category_id')
                            ->label(__('admin.Category'))
                            ->placeholder(__('admin.Select_category'))
                            ->relationship(name: 'category', titleAttribute: 'name')
                            ->options(
                                fn($get) => Category::query()
                                    ->pluck('name', 'id')
                            )
                            ->searchable()
                            ->preload()
                            ->live()
//                            ->afterStateUpdated(function($set) {
//                                $set('category_id', null);
//                            })
                           ->columnSpanFull(),
                        Forms\Components\TextInput::make('name')
                            ->label(__('admin.Game_name'))
                            ->placeholder(__('admin.Enter_name_game'))
                            ->required()
                            ->maxLength(191),
                        Forms\Components\TextInput::make('uuid')
                            ->label('UUID')
                            ->placeholder(__('admin.Enter_UUID'))
                            ->required()
                            ->maxLength(191),
                        Forms\Components\TextInput::make('type')
                            ->label(__('admin.Type'))
                            ->placeholder(__('admin.Enter_type'))
                            ->required()
                            ->maxLength(50),
                        Forms\Components\Group::make()
                            ->schema([
                                Forms\Components\TextInput::make('provider')
                                    ->label(__('admin.Provider'))
                                    ->placeholder(__('admin.Enter_provider'))
                                    ->required()
                                    ->maxLength(50),
                                Forms\Components\Select::make('provider_service')
                                    ->label(__('admin.Service_Provider'))
                                    ->options([
                                        '\Slotgen\Slotgen' => 'Slotgen',
                                    ])
                            ])->columns(2),

                        Forms\Components\FileUpload::make('image')
                            ->label(__('admin.Image'))
                            ->placeholder(__('admin.Upload_image'))
                            ->image()
                            ->columnSpanFull()
                            ->required(),
                        Forms\Components\TextInput::make('technology')
                            ->label(__('admin.Technology'))
                            ->columnSpanFull()
                            ->required(),
                        Forms\Components\Toggle::make('has_lobby')
                            ->required(),
                        Forms\Components\Toggle::make('is_mobile')
                            ->required(),
                        Forms\Components\Toggle::make('has_freespins')
                            ->required(),
                        Forms\Components\Toggle::make('has_tables')
                            ->required(),
                        Forms\Components\Toggle::make('active')
                            ->default(true)
                            ->required(),
                    ])->columns(2)
            ]);
    }

    /**
     * @param Table $table
     * @return Table
     * @throws \Exception
     */
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('uuid')
                    ->label('UUID')
                    ->searchable(),
                Tables\Columns\ImageColumn::make('image'),
                Tables\Columns\TextColumn::make('type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('provider')
                    ->searchable(),
                Tables\Columns\IconColumn::make('technology')
                    ->boolean(),
                Tables\Columns\IconColumn::make('has_lobby')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_mobile')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->boolean(),
                Tables\Columns\IconColumn::make('has_freespins')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->boolean(),
                Tables\Columns\IconColumn::make('has_tables')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->boolean(),
                Tables\Columns\IconColumn::make('active')
                    ->boolean(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('Category')
                    ->relationship('category', 'name')
                    ->label(__('admin.Select_category'))
                    ->indicator('Categoria'),
                Filter::make('created_at')
                    ->form([
                        DatePicker::make('created_from')->label('Data Inicial'),
                        DatePicker::make('created_until')->label('Data Final'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['created_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '>=', $date),
                            )
                            ->when(
                                $data['created_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '<=', $date),
                            );
                    })
                    ->indicateUsing(function (array $data): array {
                        $indicators = [];

                        if ($data['created_from'] ?? null) {
                            $indicators['created_from'] = __('admin.Initial_Creation') . Carbon::parse($data['created_from'])->toFormattedDateString();
                        }

                        if ($data['created_until'] ?? null) {
                            $indicators['created_until'] = __('admin.Final_Creation') . Carbon::parse($data['created_until'])->toFormattedDateString();
                        }

                        return $indicators;
                    }),
                Tables\Filters\SelectFilter::make('provider')
                    ->label(__('admin.Provider'))
                    ->options([
                        'Evoplay' => 'Evoplay',
                        'PGSoft' => 'PGSoft',
                    ])
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkAction::make('Ativar')
                    ->icon('heroicon-m-check')
                    ->requiresConfirmation()
                    ->action(function($records) {
                        return $records->each->update(['active' => 1]);
                    }),
                Tables\Actions\BulkAction::make('Desativar')
                    ->icon('heroicon-m-x-circle')
                    ->requiresConfirmation()
                    ->action(function($records) {
                        return $records->each(function($record) {
                            $id = $record->id;
                            Game::where('id', $id)->update(['active' => 0]);
                        });
                    }),
                Tables\Actions\BulkActionGroup::make(env('APP_DEMO') ? [] :[
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [

        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListGames::route('/'),
            'create' => Pages\CreateGame::route('/create'),
            'edit' => Pages\EditGame::route('/{record}/edit'),
        ];
    }
}
